# unstable_features = true
array_width = 80
attr_fn_like_width = 80
# binop_separator = "Back"
# blank_lines_lower_bound = 0
# blank_lines_upper_bound = 1
# brace_style = "PreferSameLine"
chain_width = 80
# comment_width = 60
# condense_wildcard_suffixes = true
edition = "2021"
# empty_item_single_line = true
# enum_discrim_align_threshold = 20
fn_args_layout = "Compressed"
fn_call_width = 40
# fn_single_line = true
force_explicit_abi = true
# force_multiline_blocks = true
# format_code_in_doc_comments = true
# format_macro_matchers = true
# format_macro_bodies = true
# format_strings = true
hard_tabs = false
# hex_literal_case = "Upper"
# imports_indent = "Visual"
# imports_layout = "HorizontalVertical"
# indent_style = "Block"
# inline_attribute_width = 60
# match_arm_blocks = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 80
merge_derives = true
# imports_granularity = "Crate"
newline_style = "Windows"
# normalize_comments = true
# normalize_doc_attributes = false
# overflow_delimited_expr = true
remove_nested_parens = true
# reorder_impl_items = true
reorder_imports = true
# group_imports = "StdExternalCrate"
reorder_modules = true
short_array_element_width_threshold = 80
# skip_children = false
# space_after_colon = true
# space_before_colon = false
# spaces_around_ranges = false
# struct_field_align_threshold = 5
# struct_lit_single_line = true
struct_variant_width = 40
tab_spaces = 2
# trailing_comma = "Vertical"
# trailing_semicolon = true
# type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
# where_single_line = true
# wrap_comments = true
use_small_heuristics = "Off"