name: Rust release check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update stable && rustup default stable
    - name: Check
      run: cargo check --release --verbose
    - name: Run tests
      run: cargo test --verbose