name: Rust development check

on:
  push:
    branches: [ "!master", "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update stable && rustup default stable
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose
  beta:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update beta && rustup default beta
    - name: Setup formatter
      run: rustup component add rustfmt --toolchain beta
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose
  nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update nightly && rustup default nightly
    - name: Setup formatter
      run: rustup component add rustfmt --toolchain nightly
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose